# Generated by Django 3.1.1 on 2020-10-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holzarbeit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bretter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brettnummer', models.CharField(max_length=100)),
                ('holzart', models.CharField(max_length=100)),
                ('laenge', models.FloatField()),
                ('breite', models.FloatField()),
                ('staerke', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Holz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheiben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheibennummer', models.CharField(max_length=100)),
                ('holzart', models.CharField(max_length=100)),
                ('durchmesser', models.FloatField()),
                ('staerke', models.FloatField()),
            ],
        ),
    ]
