# Generated by Django 3.1.1 on 2020-10-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holzarbeit', '0002_bretter_holz_scheiben'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bretter',
            new_name='Brett',
        ),
    ]
